name: Shell Scripts Unit Testing

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: bash test.sh
      shell: bash
