name: Shell Scripts Unit Testing

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Run script file
      run: |
        ls -l 
        chmod u+x ./test.sh
        ./test.sh
      
